### ISSUE TITLE
Can't fetch plugin using cordova plugin add org.disusered.safe

### ISSUE THREAD

**Issue by henry74** [disusered/cordova-safe#2]
Getting Error: 404 Not Found: org.disusered.safe

**Comment by disusered** [comment]
Can you give me any more information as to how to replicate the issue? What command did you run? Any more of the stack trace? The plugin registry migrated to npm, it may have to do with that. I'll take a look, thanks for the feedback.

**Comment by henry74** [comment]
Just typed the cordova plugin command as specified. Works for other plugins
fine.

Also what encryption method does it use?

**Comment by chi-mai2b** [comment]
Hi, I'm getting the same issue, impossible to install the plugin

    cordova plugin add https://github.com/disusered/cordova-safe

getting the error

```
Installing "com.disusered.safe" for android
Installing "com.disusered.safe" dependencies
Error during processing of action! Attempting to revert...
Failed to install 'com.disusered.safe':Error: Uh oh!
"APP_FOLDER\plugins\com.disusered.safe\libs\conceal-1.0.0\libs\conceal-1.0.0.jar" not found!
    at Object.module.exports.common.copyFile (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.js:38:40)
    at Object.module.exports.common.copyNewFile (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.js:69:16)
    at Object.module.exports.source-file.install (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:78:20)
    at installWrapper (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:76:32)
    at Object.ActionStack.process (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:543:20)
    at USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
    at _fulfilled (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (USER_FOLDER\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
```

Windows 7 x64, 
Git Bash
```
$ npm --version
1.4.3
$ cordova --version
5.0.0
```

**Comment by chi-mai2b** [comment]
Ok I got it solved !

For anyone interested, here's the steps done:

1. `git clone https://github.com/disusered/cordova-safe.git`
2. `git checkout origin/master`
3. [Install gradle](https://docs.gradle.org/current/userguide/installation.html)
4. Build the project
5. Install the plugin from local repo `cordova plugin add ../path/to/local/cordova-safe/`

**Comment by disusered** [comment]
Thanks for the workaround! I tried automating the gradle step but as noted, it is not solid. Since then, cordova-android was updated and has native gradle support for plugins. I've been incredibly busy, but will try to get around to updating my plugins to use the newer, standard interfaces for third party android code.

**Comment by disusered** [comment]
Finally got around to this, plugin.xml checks if cordova-android and plugman are new enough and if so, adds the the Maven dependency via <framework> tags as noted in http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html
