### ISSUE TITLE
java.lang.ClassNotFoundException: com.disusered.Safe

### ISSUE THREAD

**Issue by cojomojo** [disusered/cordova-safe#5]
Hi, I am trying out the plugin (using your example in the readme), but I keep getting this error in adb logs:

```
W/System.err(30861): java.lang.ClassNotFoundException: com.disusered.Safe
W/System.err(30861): 	at java.lang.Class.classForName(Native Method)
W/System.err(30861): 	at java.lang.Class.forName(Class.java:308)
W/System.err(30861): 	at java.lang.Class.forName(Class.java:272)
W/System.err(30861): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:487)
W/System.err(30861): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:167)
W/System.err(30861): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:120)
W/System.err(30861): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
W/System.err(30861): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err(30861): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(30861): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err(30861): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(30861): 	at android.os.Looper.loop(Looper.java:135)
W/System.err(30861): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err(30861): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.disusered.Safe" on path: DexPathList[[zip file "/data/app/io.cordova.hellocordova-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
W/System.err(30861): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err(30861): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
W/System.err(30861): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
W/System.err(30861): 	... 13 more
W/System.err(30861): 	Suppressed: java.lang.ClassNotFoundException: com.disusered.Safe
W/System.err(30861): 		at java.lang.Class.classForName(Native Method)
W/System.err(30861): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
W/System.err(30861): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
W/System.err(30861): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
W/System.err(30861): 		... 14 more
W/System.err(30861): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
I/System.out(30861): Error adding plugin com.disusered.Safe.
W/System.err(30861): java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
W/System.err(30861): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
W/System.err(30861): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:120)
W/System.err(30861): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
W/System.err(30861): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err(30861): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err(30861): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err(30861): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(30861): 	at android.os.Looper.loop(Looper.java:135)
W/System.err(30861): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

I use the cordova cli, and tried removing and readding the plugin as well as removing and readding the android platform, still no luck. I ran the app on the emulator as well as my android device (both running 5.1).

**Comment by disusered** [comment]
There were issues migrating to Cordova 5 and Gradle. I am addressing them now, I am trying to finish by tomorrow. After that I need to fix iOS dependencies, and I will release when both are fixed. 

Thanks for the report, and I apologize for the delay! I will update this thread when the plugin fixes are published.

**Comment by disusered** [comment]
Issue is solved in develop but iOS is not addressed yet. Once I fix that I will publish a new release and close this ticket.
